ral-facilities/operationsgateway-api

operationsgateway_api/src/models.py
A one-liner to remove a TODO. I've spent quite a while trying to recreate a UTF8 error that I came across a few months ago when ingesting some non dev server data but I haven't been able to recreate it. I think it's best to remove the TODO and see if it reappears when the simulated EPAC data is given to us in a few months time
=> DSEGOG-219 Remove TODO

operationsgateway_api/src/routes/images.py, operationsgateway_api/src/routes/records.py, operationsgateway_api/src/routes/waveforms.py
This JIRA issue is to fix the bugs on the OpenAPI interface caused by some of the conflicting examples. As we use Postman now to document our examples to demonstrate the potential functionality of the API, removing the query parameter examples seems like the best way to resolve the OpenAPI usage issues without spending hours effectively replicating the examples we provide in the Postman collection
=> DSEGOG-45 Remove OpenAPI example query parameters

operationsgateway_api/src/records/image.py
This PR turns a TODO into a comment explaining why `Record.count_records()` hasn't been used. I can't find a clean, easy way to call `Record.count_records()` in the Image class to prevent the circular import. I think it could be done but you'd have to make a few changes across the two classes (put them into a third 'interface' type class) but honestly, I just don't think it's worth it for a single call of that function. Hence I've just explained why it hasn't been done
=> DSEGOG-214 Document why `Record.count_records()` couldn't be used

operationsgateway_api/src/models.py, operationsgateway_api/src/records/record.py, test/endpoints/test_channel_summary.py
As discussed with the frontend team, this change adds a timestamp (taken from record metadata where the data comes from) to the channel sample on the channel summary endpoint. This changes the samples from a list of values to a list of dictionaries, containing a timestamp and value. Example response:
```json
{
"first_date": "2022-04-07T14:16:16",
"most_recent_date": "2022-04-08T16:58:57",
"recent_sample": [
{"2022-04-08T14:16:16": -8582000.0},
{"2022-04-09T14:16:16": -8461000.0},
{"2022-04-10T14:16:16": -8535000.0}
]
}
```
=> DSEGOG-230 Add record timestamp to channel sample

codecov.yml
As discussed, a small change to make codecov checks less strict, in the hope that we don't make them fail as often as we sometimes do. 
I've checked the config is valid by following the instructions at https://docs.codecov.com/docs/codecov-yaml#validate-your-repository-yaml
=> DSEGOG-245 Relax codecov checks

poetry.lock
As per a recent Dependabot alert (see the security tab of this repo if you haven't seen it yet), the `certifi` dependency needs upgrading. A quick `poetry update certifi` did the trick, giving us the patched version.
=> DSEGOG-263 Upgrade `certifi` for security vulnerability

operationsgateway_api/src/error_handling.py
Whilst doing some development the other day, I caused an unintended `AttributeError` in a try/except block where an `ExperimentDetailsError is raised. This is the [try/except block in question](https://github.com/ral-facilities/operationsgateway-api/blob/main/operationsgateway_api/src/experiments/experiment.py#L101). 
When the code executed, I had the following log:
```python
ERROR:   Error in endpoint 'store_experiments_from_scheduler': 'NoneType' object has no attribute 'parts'
```
This wasn't very helpful as I wasn't actually sure where this was coming from, so I spent a little while tracking down where I had gone wrong. This PR should resolve this in the future - any exceptions that are caught by our decorator will now log the traceback. So the same error now logs the following: …
=> Improve exception logging when API exception is caught

operationsgateway_api/src/routes/records.py, test/endpoints/test_get_records.py
This PR fixes a bug found by the frontend team where a user gets a 500 response on `/records` when using a projection that doesn't include channels (i.e. `projection=metadata`).
This bug was caused because the function that applies false colour to image thumbnails was called no matter what comes back from the database. That function needs the `channels` key-value pair - if you're projecting `metadata` only, obviously you'll have no channel data. I've added a couple of if statements in the relevant places to fix this; the function will only be called when there's channel data now.
I've added a couple of integration tests so we have test scenarios of this situation so we don't cause this bug in the future.
=> DSEGOG-265 Fix projections bug on /records

operationsgateway_api/src/experiments/experiment.py, operationsgateway_api/src/models.py, operationsgateway_api/src/routes/experiments.py, test/endpoints/test_get_experiments.py, test/experiments/scheduler_mocking/experiments_mocks.py, test/experiments/test_experiment.py
This PR changes the `_id` in the `ExperimentModel` to use `ObjectId`s. Previously, this field was filled with a concatenation of the experiment ID and the part number. However, in the simulated EPAC data, experiment IDs for maintenance periods are stored as `maintenance`. In the case of the generated data, they were all experiments with a part number of 1.
Given current discussions regarding parts, it's unclear if this'll be the case in production so I've decided to move to using ObjectIds. We use these in the user session functionality so wasn't too bad to make this change (I was a bit scared of them before). Even the tests didn't require too much work!
=> DSEGOG-261 Use ObjectIds in ExperimentModel

.flake8, operationsgateway_api/src/routes/common_parameters.py, operationsgateway_api/src/routes/records.py
In this API, we have a few query parameters where we want to accept JSON objects as inputs (which are cast to dictionaries). Up to now, we've used `fastapi.Depends` to run a custom JSON parser (`QueryParameterJSONParser`, it just runs `json.loads`) but I've recently discovered `pydantic.Json` which can do the same job for us and means we can remove the dependency injection and the `QueryParameterJSONParser` class!
I had the idea from [someone's blog](https://roman.pt/posts/fastapi-json-query/) which I haven't come across up until now.
This PR makes the change across all the query parameters where we want JSON objects as input and removes the code that's no longer needed. It looks good on the OpenAPI interface, which now suggests the input is a JSON string or an `OrderedMap` - seems to …
=> Change JSON query parameters to use pydantic.Json

.github/workflows/ci.yml
I noticed that when GitHub Actions fails, the bucket that's created at the start of the job isn't cleaned up. This was happening because the steps . This PR fixes that bug by adding an extra condition to the if statement so buckets are removed if a step fails. You can see this works on the following run where I forced a failure in the CI job - https://github.com/ral-facilities/operationsgateway-api/actions/runs/6394539896/job/17356143894
=> DSEGOG-270 Fix cleanup of Echo buckets

.github/ci_config.yml, operationsgateway_api/config.yml.example, operationsgateway_api/src/config.py, operationsgateway_api/src/experiments/experiment.py, operationsgateway_api/src/experiments/scheduler_interface.py, operationsgateway_api/src/models.py, test/experiments/test_experiment.py, test/experiments/test_scheduler_interface.py
This PR allows the API to contact the Scheduler and ask for details on experiments that take place on multiple instruments where previously, only data about one instrument could be retrieved. In the config, the instruments that the API contacts are configured using by specifying the instrument names in list. In the example we currently have a single instrument but I expect that to be two in production (EA1 & EA2). 
`get_experiments_from_scheduler()` is a good place to start looking at the changes - the code now iterates through the list of configured instrument names and sends a call per instrument to the Scheduler for experiments on that instrument within the relevant start and end dates.
`_map_experiments_to_part_numbers()` now returns a list of `ExperimentPartMappingModel`, a new …
=> DSEGOG-258 Multiple Instrument Support for Experiments Functionality

poetry.lock, pyproject.toml
removed pytest-async from the dependency part of the pyproject file but kept it in the dev-dependency
=> DSEGOG-280 edit pytest-async dependency

.github/workflows/ci.yml, util/ingest_hdf.py
With the introduction of running tests on Python 3.10 & 3.11, Ubuntu 22.04 runners need to be used. In these runners, Ubuntu have removed mongodb from being installed in 22.04, hence the Actions runner image also not having it. We use the `supercharge/mongodb-github-action@1.7.0` action to start the database as they are "available from within the MongoDB docker container. But not directly on the 22.04 host" (https://github.com/supercharge/mongodb-github-action/issues/39#issuecomment-1328008609). 
Someone has found a solution to install `mongosh` on their CI (see https://github.com/actions/runner-images/issues/6626#issuecomment-1327744126) and I've adapted their commands to install `mongoimport` instead). I've made use of `mongoimport` in the `ingest_hdf.py` script as it serves as a good …
=> DSEGOG-300 Add mongoimport back to GitHub Actions

util/og_api_postman_collection.json
The Postman collection still references Gemini data (through channel names, IDs etc.) and now the main branch contains the simulated data stuff, we should move to use this in the Postman collection. This PR makes all relevant changes to make that move.
To test this PR, export the Postman collection to your Postman application and test each of the endpoints with the query parameters and ensure they work. There's one query parameter that won't work in `GET /records`, specifically `{"_id": {"$eq": "20230604000000"}}`. This is due to a bug in the API. An issue has been created for this in Jira (DSEGOG - 303) so it's fine that it doesn't work, it'll be resolved when that issue is fixed.
If you haven't moved to simulated data yet, please use the following guide to get that data in your …
=> DSEGOG-302 Update Postman collection to use simulated CI data

.github/ci_ingest_echo_config.yml, util/realistic_data/config.yml.example, util/realistic_data/ingest/config.py, util/realistic_data/ingest_echo_data.py
This is a small PR to pre-empt an issue that I might find when re-ingesting the data on the dev server. It allows you to work with instances of the API which use https, something which the dev server now does.
This change has only been made on the new script. It doesn't need to be made on `ingest_hdf.py` as when you don't want the script to launch an instance of the API (i.e. you want to use an instance already alive), you specify the entire URL using the `-u` option (which includes the http part)
=> DSEGOG-304 Add flag to allow an API instance to be pointed to https

test/endpoints/test_export.py
Following the independent merges of #104 and #103 , one the tests added in the former is not compatible with the latter. As a result, the phashes for this test need to be slightly updated.
Also added assert message (to make determining which file in the zip is the one for which the error is occuring easier).
Went through the motions to double check 20230605080000_FE-204-PSO-CAM-1.png, but did not bother for the other timestamps.
Has max pixel value of 2708 as a signed `int32`.
Input vmin, vmax: 5, 15
Scaled vmin, vmax: 1285, 3855
Subtract vmin: Max value maps to 1423 in range 0 <= x <= 2570
Scale by vmax: Max value maps to 141.7 in range 0 <= x <= 255 
Input vmin, vmax: 5, 15
Scaled vmin, vmax: 1280, 4095
Subtract vmin: Max value maps to 1428 in range 0 <= x <= 2815
Scale by vmax: Max …
=> Update export tests to account for new depth scaling

test/endpoints/test_get_experiments.py, test/endpoints/test_submit_hdf.py, util/realistic_data/ingest_echo_data.py
I've fixed the bug that imports the experiments but immediately wipes the database afterwards - I've just swapped the order of these two things. I've also removed the skip on the test that wouldn't run on GitHub Actions as it is no longer relevant - the test doesn't rely on the dev scheduler so can be run on CI. I removed a couple of commented out skips too.
To test, I ran the ingest script with the `wipe_database` config option set to true and then ran the tests.
=> DSEGOG-334 Fix bug relating to experiments on ingest script

operationsgateway_api/src/models.py, test/records/ingestion/create_test_hdf.py
This PR fixes the warnings that `pytest` picked up while running the tests. There were two types of warnings that got fixed:
- `PydanticDeprecatedSince20: Support for class-based config is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0.`
- `FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison`
The Pydantic warning just needed the config for `WaveformModel` migrating to the new format (I think this was just left over from when the migration previously took place. The elementwise comparison was `numpy` complaining that it was comparing a `numpy` array with a string - I added in a type check before the if statement continues with the comparison.
To test, run the tests and ensure …
=> DSEGOG-283 Fix test warnings

.github/ci_config.yml, operationsgateway_api/config.yml.example, operationsgateway_api/src/config.py, operationsgateway_api/src/main.py
This PR adds the `url_prefix` to the config which sets the root path of the FastAPI `api` object created in `main.py`. This allows us to match the root path of `/api` when the API is deployed on the dev server and in turn, this means the OpenAPI interface works again on there - it gave a 404 previously.
The `app` section of this config is now mandatory so that's a minor change as a result of this PR. The example config is set to `""` because for development, the API is hosted on `/`, but for the dev server, `/api` will be set for this config option. A corresponding Ansible PR will be made to manage those types of changes.
=> DSEGOG-327 Add `url_prefix` to API for OpenAPI docs

util/realistic_data/daily_ingestor.py, util/realistic_data/ingest/api_client.py
This PR fixes an issue I've noticed on the daily ingestion of simulated data where the ingestion can't quite keep up with the cron job scheduled for every 60 seconds, thereby causing some errors when both try to ingest the same file. When there are multiple files to be ingested by `daily_ingestor.py`, the script loops through each of the files, ingesting them one at a time. Sometimes, ingesting all of the files in the list takes over 60 seconds. As such, the second execution of the script can try to ingest files that the first execution is ingesting which can throw up errors because the file can’t be found (as the first execution has finished the ingestion by that point and deletes the file).
This is resolved by creating a temporary directory where the files due to be ingested are stored …
=> DSEGOG-337 Fix daily ingestor script trying to ingest the same file twice

.github/workflows/ci.yml, noxfile.py, operationsgateway_api/src/records/ingestion/channel_checks.py
This PR fixes an issue I noticed with the CI while sorting out #140. The flake8 CI job failed and when I looked at the black job, I noticed that it reformatted some files but the job passed. This is because black "exits with code 0 unless an internal error occurred or a CLI option prompted it" (https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#the-basics).
For development, that behaviour is fine, but it's not optimal for CI - when black spots an issue and reformats the file, the job should fail. That's the behaviour I've implemented with this PR.
To test, go to your source code locally and cause an intentional formatting issue (e.g. make a line longer than 88 characters by lengthening a variable name). Then run the same command used on the CI (`nox -s black -- …
=> DSEGOG-343 Fix black CI job not failing when it finds an issue

.github/ci_config.yml, operationsgateway_api/config.yml.example, operationsgateway_api/maintenance.json.example, operationsgateway_api/scheduled_maintenance.json.example, operationsgateway_api/src/config.py, operationsgateway_api/src/main.py, operationsgateway_api/src/models.py, operationsgateway_api/src/routes/maintenance.py, operationsgateway_api/src/users/user.py, test/endpoints/test_get_users.py, test/endpoints/test_maintenance.py, util/og_api_postman_collection.json, util/users_for_mongoimport.json
Adds two endpoints for getting and setting maintenance and scheduled maintenance messages. This follows this existing format for Sci/DataGateway. These are stored as JSON files rather than in the DB in order to allow the messages to display when the DB is not contactable.
- Added config options and example files for the (scheduled) maintenance
- Added Pydantic models for maintenance and scheduled maintenance bodies
- Since the issue only listed "info" and "warning" as severity levels expected by the frontend, these are enforced with a `StrEnum`. Can add more cases or relax this to `str` if needed.
- Added POST/GET endpoints for maintenance and scheduled maintenance
- To cut I/O, these use the [lru_cache](https://fastapi.tiangolo.com/advanced/settings/#lru_cache-technical-details) to cache …
=> Add /maintenance and /maintenance/scheduled GET, POST endpoints

.flake8, operationsgateway_api/src/records/echo_interface.py, operationsgateway_api/src/records/export_handler.py, operationsgateway_api/src/records/image.py, operationsgateway_api/src/records/record.py, operationsgateway_api/src/records/waveform.py, operationsgateway_api/src/routes/waveforms.py, test/images/test_image.py, test/records/conftest.py, test/records/test_waveform.py, util/move_objects.py
- New images/waveforms created in Echo will use a `YYYY/MM/DD/HHMMSS` (sub)directory structure, to avoid the current situation of having ~100,000 objects in the `image` and `waveform` directories, which made listing practically impossible when e.g. debugging with `s3cmd`.
- Minor name changes/refactors to some existing methods which extracted channel_name from the image/waveform_path so that they were more consistent and intuitively named across both classes.
- In `get_image` and `get_waveform`, first try the new subdirectory structure and if that fails, default to the old structure before actually failing. This allows us to use the new structure going forward, without needing to migrate existing data.
- Minor updates to relevant tests (coverage might need checking - locally I had a mix …
=> Implement YYYY/MM/DD/HHMMSS subdirectory structure

operationsgateway_api/src/routes/records.py, test/endpoints/conftest.py, test/endpoints/test_delete_record.py
While discussing the deletion of old records in the sprint, I noticed that the `delete_record_by_id` endpoint was using the record_id directly in the Echo path. This is fine for the historical data, but since the new data goes in subdirectories by default we should try and purge both locations.
=> Update delete_by_record_id to use subdirectories

operationsgateway_api/config.yml.example, util/users_for_mongoimport.json
To check that the API is working, a script needs to be written that makes the appropriate calls and outputs the result in a format Icinga can understand. 
The API "working" is defined as being able to `/GET`, `/PUT`, `/DELETE` data from Mongo and echo. This will likely be expanded in the future to accommodate the checking of the `background_scheduler` cron job.
The python script itself will be deployed on the rig machine using the Ansible script. 
The ansible script manages credentials by storing them in a vault and then replacing the necessary auth item in the [config](https://github.com/ral-facilities/operationsgateway-ansible/blob/main/roles/operationsgateway-api/templates/config.yml.j2).
In order to keep all credentials in the same place, this PR:
-  creates the necessary user in the …
=> Adding healthcheck user

.flake8, operationsgateway_api/src/routes/ingest_data.py, test/endpoints/test_submit_hdf.py
The warnings were being displayed as a list of chars instead of a list of strings.
Now the ingest endpoint returns, for example:
`"warnings": [
"File minor version number too high (expected <=1)"
]`
I've had to suppress the linter for now and have [created an item in the backlog](https://stfc.atlassian.net/browse/DSEGOG-415) to deal with this later.
=> Dsegog 410 warning for file version number too high received as a char array instead of a string

operationsgateway_api/src/constants.py, operationsgateway_api/src/records/ingestion/hdf_handler.py, operationsgateway_api/src/records/ingestion/partial_import_checks.py, test/endpoints/test_submit_hdf.py, test/records/ingestion/create_test_hdf.py, test/records/ingestion/test_hdf_handler.py, test/records/ingestion/test_partial_import.py
While looking at the timestamp issue, which responded with a 500 if the `timestamp` key was incorrect, I found some code that suggested it should be deleted if Gemini data was no longer being used. 
Gemini data used a timestamp in the format: "%Y-%m-%d %H:%M:%S" (e.g: 2020-04-07 14:28:16) whereas the [EPAC data sim](https://github.com/CentralLaserFacility/EPAC-DataSim/blob/47fe5de1b89d81aaf6943e7c58b0c3fedae1a04f/src/epac_data_sim/writer.py#L21) produces timestamps which are ISO8601 compliant, which matches the Interface Exchange Spec ([page 2](https://stfc365.sharepoint.com/:w:/r/sites/CLFDataDiscoveryAndExperimentalDataManagement/_layouts/15/Doc.aspx?sourcedoc=%7B27352519-B7BC-4CCC-96D9-45A37BFBF5E9%7D&file=OpsGateway%20data%20interchange%20format.docx)) .
However, I was looking at …
=> Dsegog 411 problems with timestamp give unknown error instead of useful details

operationsgateway_api/src/records/record.py, operationsgateway_api/src/routes/channels.py, test/endpoints/test_channel_summary.py, test/records/test_record.py
The new wavefront types (`FLOAT_IMAGE` and `VECTOR`) were missing from the if/elif block for requests to `/channels/summary`. Have added these, along with a warning if the channel dtype is unrecognised. I considered making it throw an error (since the dtype should be well controlled) but the existing tests assert that this is an empty list so I left the functionality as is.
=> Add wavefront channel types to /channels/summary

operationsgateway_api/src/records/false_colour_handler.py, operationsgateway_api/src/routes/records.py, test/endpoints/test_channel_summary.py
While ingesting wavefront data to the dev instance, noticed that the thumbnail for the float image uses `viridis`:
Despite the fact that the "system default" for floats should be `bwr`:
https://github.com/ral-facilities/operationsgateway-api/blob/8955ad50b418149a575222f738347497c219ef7f/operationsgateway_api/config.yml.example#L25
Having looked into it, this was a combination of not calling `FloatImage.get_preferred_colourmap()` in the records endpoints and the fact that if a user pref isn't found, both the method for traditional and floating point images were returning `None`. MatPlotLib defaults to `viridis` if `None` is passed:
```python
>>> import matplotlib.pyplot as plt
>>> plt.cm.get_cmap(None).name
'viridis'
```
Which is undetectable for the traditional images where the "system …
=> Return system defaults from get_preferred_colourmap and get_preferred_float_colourmap
